### ISSUE TITLE
Publish the helm chart to a helm repo

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-helm#110]
it would be nice to have the helm chart published here https://artifacthub.io/packages/search?kind=0

Then getting new versions and users always getting the latest versions will be easier. Right now the docs tell us to do this:
```
# Set the Weaviate chart version
export CHART_VERSION="v15.0.0"
# Download the Weaviate Helm chart
wget https://github.com/weaviate/weaviate-helm/releases/download/$CHART_VERSION/weaviate.tgz
# Download an example values.yml (with the default configuration)
wget https://raw.githubusercontent.com/weaviate/weaviate-helm/$CHART_VERSION/weaviate/values.yaml
# Create a Weaviate namespace
$ kubectl create namespace weaviate

# set the desired Weaviate version
export WEAVIATE_VERSION="1.17.2"

# Deploy
$ helm upgrade \
  "weaviate" \
  weaviate.tgz \
  --install \
  --namespace "weaviate" \
  --values ./values.yaml \
  --set "image.tag=$WEAVIATE_VERSION"
```

Issues with this approach:
- The docs are always outdated since right now v15.4.0 would be the latest version
- more steps
- People have to download the chart locally and sometimes seem to get the location incorrect (saw that on slack once)

What would be nicer instead:
```
helm repo add weaviate https://weaviate.github.io/helm-charts
helm install my-weaviate-stack weaviate/weaviate
```
^^ which would automatically use the latest published chart

**Comment by samos123** [comment]
I'm confused now. Looks like there is already a repo published here:
```
helm repo add weaviate https://weaviate.github.io/weaviate-helm
helm search repo weaviate
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
weaviate/weaviate       15.4.0          1.15.0          A Helm Chart to run Weaviate with all dependencies
```

So why are the instructions not using that repo instead?

**Comment by samos123** [comment]
Seems all that's needed is for someone to publish this file to gh-pages branch: https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml

after apply for ownership claim so the helm chart can be listed as official image

**Comment by StefanBogdan** [comment]
@samos123 I will add them [artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml)  to the `gh-pages` branch.

Do we need it in `main` as well?

**Comment by StefanBogdan** [comment]
We have a page with instructions as well: https://weaviate.github.io/weaviate-helm/

**Comment by StefanBogdan** [comment]
@samos123 do we need the [artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) in the `master` branch as well?

I think we can close this issue now, feel free to open.

**Comment by samos123** [comment]
it seems it's not marked as the official verified package: https://artifacthub.io/packages/helm/weaviate/weaviate

Looks like it may need to be in the master branch and someone that's listed as the owner needs to claim ownership:
![image](https://user-images.githubusercontent.com/388784/223129246-f78bb1e8-d1ee-4c66-b913-6208af12bfeb.png)
