### ISSUE TITLE
Use workload identity for GCS backups in GKE

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-helm#114]
it should be possible to use workload identity for GCS backups instead of relying on passing JSON keys. Many large enterprise have an org policy that prevents them from downloading JSON keys for service accounts.

https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

**Comment by StefanBogdan** [comment]
I see that the Workload Identity is set using a `serviceAccount` which is now possible to set: https://github.com/weaviate/weaviate-helm/blob/master/weaviate/values.yaml#L50-L54

I am closing it. Feel free to open if needed.
