### ISSUE TITLE
How to pass api key as a secret

### ISSUE THREAD

**Issue by liorhar** [weaviate/weaviate-helm#133]
Instead of specifying a plain text API key, is it possible to reference a Kubernetes secret?

**Comment by StefanBogdan** [comment]
Yes, since the API keys are ENV Vars you can add it to [envSecrets](https://github.com/weaviate/weaviate-helm/blob/master/weaviate/values.yaml#L151) and read the value from a Secret. like this:
```
envSecrets:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: <secret-name-that-contains-AUTHENTICATION_APIKEY_ALLOWED_KEYS-as-a-key-and-the-keys-as-values>
```

**Comment by StefanBogdan** [comment]
It will make it more descriptive in `values.yml`.

**Comment by StefanBogdan** [comment]
This is already documented in the `values.yaml`. Closing.
