### ISSUE TITLE
autoscaled pod is going into readiness failed error, while using efs volume as persistent volume

### ISSUE THREAD

**Issue by shivam1410** [weaviate/weaviate-helm#148]
pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0109b7cba15479c81
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
```
storageclass.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
```

uncommented the following code code in template/statefulset.yaml
```
- name: weaviate-persistence-data-vol
          persistentVolumeClaim:
            {{ if empty .Values.storage.fullnameOverride }}
            claimName: weaviate-persistence-data
            {{ else }}
            claimName: {{ .Values.storage.fullnameOverride }}
            {{ end }}
```
and using this volume as persistent volume,

Gettting this error when a weaviate pod scales up
```
Readiness probe failed: Get "http://192.168.57.201:8080/v1/.well-known/ready": dial tcp 192.168.57.201:8080: connect: connection refused
```

```netstat -tulpn | grep LISTEN ```
Result of netstat command run inside the container - weaviate-0

```
tcp        0      0 :::50051                :::*                    LISTEN      1/weaviate
tcp        0      0 :::6060                 :::*                    LISTEN      1/weaviate
tcp        0      0 :::8080                 :::*                    LISTEN      1/weaviate
tcp        0      0 :::7000                 :::*                    LISTEN      1/weaviate
tcp        0      0 :::7001                 :::*                    LISTEN      1/weaviate
```

Result of netstat command run inside the container - weaviate-1

```
tcp        0      0 :::6060                 :::*                    LISTEN      1/weaviate
tcp        0      0 :::7000                 :::*                    LISTEN      1/weaviate
```

**Comment by shivam1410** [comment]
@antas-marcin

**Comment by shivam1410** [comment]
@StefanBogdan

**Comment by shivam1410** [comment]
Just went through these two commits to know why you might have added feature for user defined persistent volume and then removed it. Developer forget to remove the comment added in version 13.2.1 in values.yaml.

gh-45 Add check for persistent volume claim existance: [https://github.com/weaviate/weaviate-helm/pull/46](https://github.com/weaviate/weaviate-helm/pull/46)
old version: 13.2.0
new version: 13.2.1
commit: [717cb40](https://github.com/weaviate/weaviate-helm/commit/717cb408178323421403f85b86340613d26b0900)

and 
Horizontal scaling : [https://github.com/weaviate/weaviate-helm/pull/52](https://github.com/weaviate/weaviate-helm/pull/52)
old version: 13.4.0
new version: 14.0.0-rc.0
commit: [77810de](https://github.com/weaviate/weaviate-helm/commit/77810de0b4c5b6b41c20fdd40ef9415571150899)

@StefanBogdan @antas-marcin

**Comment by antas-marcin** [comment]
@shivam1410 which version of helm charts are you using? and what does `kubect describe pod weaviate-0` tells you?

**Comment by shivam1410** [comment]
@antas-marcin 
```
apiVersion: v2
appVersion: 1.19.1
description: A Helm Chart to run Weaviate with all dependencies
home: https://github.com/weaviate/weaviate
icon: https://raw.githubusercontent.com/weaviate/weaviate/19de0956c69b66c5552447e84d016f4fe29d12c9/docs/assets/weaviate-logo.png
name: weaviate
type: application
version: 16.3.0
```
`kubectl describe pod Weaviate-0`
```
Name:             weaviate-0
Namespace:        weaviate
Priority:         0
Service Account:  default
Node:             ip-192-168-79-116.us-west-2.compute.internal/192.168.79.116
Start Time:       Tue, 30 May 2023 21:02:44 +0530
Labels:           app=weaviate
                  app.kubernetes.io/managed-by=helm
                  app.kubernetes.io/name=weaviate
                  controller-revision-hash=weaviate-7647c8dbf8
                  statefulset.kubernetes.io/pod-name=weaviate-0
Annotations:      checksum/config: afd1a2f41321078026750ff7395e4418b073a86658409e1a2ce7b77efe371c5b
Status:           Running
IP:               192.168.77.161
IPs:
  IP:           192.168.77.161
Controlled By:  StatefulSet/weaviate
Containers:
  weaviate:
    Container ID:  containerd://665513f85470715141522b084699bf975fd5577be1a1552734e792b2e7e2decf
    Image:         docker.io/semitechnologies/weaviate:1.18.0
    Image ID:      docker.io/semitechnologies/weaviate@sha256:96fc29ba6a309f9f6e3de5dc1cc0b90eb21141e7206cf8b68afb7c4628c81607
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /bin/weaviate
    Args:
      --host
      0.0.0.0
      --port
      8080
      --scheme
      http
      --config-file
      /weaviate-config/conf.yaml
      --read-timeout=60s
      --write-timeout=60s
    State:          Running
      Started:      Tue, 30 May 2023 21:02:50 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     300m
      memory:  500Gi
    Requests:
      cpu:      200m
      memory:   300Mi
    Liveness:   http-get http://:8080/v1/.well-known/live delay=900s timeout=3s period=10s #success=1 #failure=30
    Readiness:  http-get http://:8080/v1/.well-known/ready delay=10s timeout=3s period=10s #success=1 #failure=3
    Environment:
      CLUSTER_DATA_BIND_PORT:                7001
      CLUSTER_GOSSIP_BIND_PORT:              7000
      GOGC:                                  100
      PROMETHEUS_MONITORING_ENABLED:         false
      QUERY_MAXIMUM_RESULTS:                 100000
      REINDEX_VECTOR_DIMENSIONS_AT_STARTUP:  false
      TRACK_VECTOR_DIMENSIONS:               false
      STANDALONE_MODE:                       true
      PERSISTENCE_DATA_PATH:                 /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE:             text2vec-transformers
      ENABLE_MODULES:                        text2vec-transformers
      TRANSFORMERS_INFERENCE_API:            http://transformers-inference.weaviate.svc.cluster.local:8080
      CLUSTER_JOIN:                          weaviate-headless.weaviate.svc.cluster.local
    Mounts:
      /var/lib/weaviate from weaviate-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-whqbt (ro)
      /weaviate-config from weaviate-config (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  weaviate-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  weaviate-data-weaviate-0
    ReadOnly:   false
  weaviate-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      weaviate-config
    Optional:  false
  kube-api-access-whqbt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               2m34s                default-scheduler        Successfully assigned weaviate/weaviate-0 to ip-192-168-79-116.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  2m32s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c6a95616-6472-4e33-a0f6-fcc367887fc4"
  Normal   Pulled                  2m28s                kubelet                  Container image "docker.io/semitechnologies/weaviate:1.18.0" already present on machine
  Normal   Created                 2m28s                kubelet                  Created container weaviate
  Normal   Started                 2m28s                kubelet                  Started container weaviate
  Warning  Unhealthy               39s (x11 over 2m9s)  kubelet                  Readiness probe failed: Get "http://192.168.77.161:8080/v1/.well-known/ready": dial tcp 192.168.77.161:8080: connect: connection refused
```

Although I can see the pod running and can check by calling the API on the same
<img width="488" alt="image" src="https://github.com/weaviate/weaviate-helm/assets/33784139/a40c5fd2-22f9-43d1-9a54-68b961a7cbcd">

**Comment by shivam1410** [comment]
It's creating `weaviate-data-weaviate-0` claim, and not using the claim I have created, and mentioned in storage.fullNameOverride

**Comment by StefanBogdan** [comment]
Hi @shivam1410 , the reason we removed the user defined PVCs is because Weaviate needs separate PVs for each Pod. Having a `volumeClaimTemplates` allows the StatefulSet to  provision a new PV for the Pods whenever the replica set is upscaled. Doing so with user defined PVCs will make the PVC attached to all the pods (shared PV) which is not the desired Weaviate configuration.

If you want to use the EFS, why not specify the storage class like this in `values.yaml`?:
```yaml
storage:
  storageClassName: efs-sc
```

**Comment by shivam1410** [comment]
Hi @StefanBogdan @antas-marcin  We need just one volume attached to one or more scaled pods.

**Comment by StefanBogdan** [comment]
@shivam1410 I think that [these](https://github.com/weaviate/weaviate-helm/blob/master/weaviate/values.yaml#L80-L82) lines we just forgot to remove because we need a single volume per Pods.

If you want to use a single Volume for all Pods you have to comment out the `volumeClaimTemplates`, uncomment the ones that you already did:
```
       - name: weaviate-persistence-data-vol
          persistentVolumeClaim:
            {{ if empty .Values.storage.fullnameOverride }}
            claimName: weaviate-persistence-data
            {{ else }}
            claimName: {{ .Values.storage.fullnameOverride }}
            {{ end }}
```
AND to attach this Volume to a specific path, modify [this](https://github.com/weaviate/weaviate-helm/blob/master/weaviate/templates/weaviateStatefulset.yaml#L278-L279C41) to be the name of your claim.

Why do you want a single Volume for all Pods? The data is persistent with one volume per pod as well, if one pod dies the PV and its PVC will be retained and whenever the Pod restarts it attaches it back. Having one Volume could be very disadvantageous:
1. Breaks the High Availability.
2. If the volume is unavailable for some time the whole Weaviate is unavailable.
3. Multiple Weaviate instance writing/ reading from the same volume might hit the Volume throughput and become the bottleneck.

Also we prefer EBS instead of EFS because EFS is very slow compared to EBS and can become the bottleneck when querying data. Is there a reason to use EFS?

**Comment by shivam1410** [comment]
In our use case, we needed single volume so that all pods could store vectorised information at one point, because this information is updated incrementally on each user query, and that user query could be made from any pod.
If user make a query, despite which pod processed it, or made the vector for that data, data should be available in through all the pods.

if only one pod is connected to one volume, say pod1 <-> volume1, and pod2 <-> volume2, then the information that's present in volume 1 is not available to pod 2.

**Comment by shivam1410** [comment]
I already tried doing what you suggested in your latest answer, uncommenting the code and changing the volume reference, but while pod scaling up I started seeing the readiness error for newly scaled pod 2, and that was because despite the new pod 2 has data in /var/lib/weaviate/ but it's not able to run the application on port 8080, so the api to check the readiness or liveness never returns success.

**Comment by StefanBogdan** [comment]
@shivam1410 regarding this:
> if only one pod is connected to one volume, say pod1 <-> volume1, and pod2 <-> volume2, then the information that's present in volume 1 is not available to pod 2.

This is not how Weaviate works. When a Pod receives a request it forwards it to all the pods then the answers from all the pods is aggregated and sent back. Weaviate is a StatefulSet not a Deployment so each Pod is aware of the other pods and no matter which Pod receives the request, the answer will be the same. With Weaviate you do NOT need to hit a specific Pod if you want data from it, Weaviate will return the data from other volumes too.

**Comment by shivam1410** [comment]
<img width="624" alt="image" src="https://github.com/weaviate/weaviate-helm/assets/33784139/bfa1baa9-4e8f-484d-994e-952595d317a6">

**Comment by vishalrv1904** [comment]
> I already tried doing what you suggested in your latest answer, uncommenting the code and changing the volume reference, but while pod scaling up I started seeing the readiness error for newly scaled pod 2, and that was because despite the new pod 2 has data in /var/lib/weaviate/ but it's not able to run the application on port 8080, so the API to check the readiness or liveness never returns success.

Facing the same issue while running multiple pods.
Readiness probe failed: Readiness probe failed: Get "http://(IP):8080/v1/.well-known/ready": dial TCP (IP):8080: connect: connection refused

**Comment by StefanBogdan** [comment]
Hi @shivam1410 .
>How, when we have different pods running(i'll call them servers), a request is not sent to just one pod, rather all, and hence the checking for vectors is done in all volumes, and not just one?
The request goes to one of the Pods and that Pod internally forwards it to the other weaviate Pods. Weaviate has a Gossip and a Data port that is used for this. https://github.com/weaviate/weaviate-helm/blob/master/weaviate/values.yaml#L186-L187 This allow Pods to discover each other and transfer data between them.

Regarding [this](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1571627327) it means that once you scaled weaviate replicas up and ingested data then you should NOT scale down.

**Comment by StefanBogdan** [comment]
Hi @vishalrv1904

>So I have to use EFS as the persistent volume, so it would be great if there is an option on Weaviate to specify the single volume claim for all the pods. As per my understanding, we can have one PV to one PVC mapping and one PVC to many pod mapping.

Does [this](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1569781401) solution work for you? If not, what would be the reason to have a single PV?

**Comment by vishalrv1904** [comment]
No @StefanBogdan when the second pod spins up I am facing the same error.
And also tried [this](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1570001031) but facing the below exception when the pod spins up.

``` Readiness probe failed: Get "http://<IP>:8080/v1/.well-known/ready": dial TCP <IP>:8080: connect: connection refused ```

**Comment by vishalrv1904** [comment]
> Hi @vishalrv1904
> 
> > So I have to use EFS as the persistent volume, so it would be great if there is an option on Weaviate to specify the single volume claim for all the pods. As per my understanding, we can have one PV to one PVC mapping and one PVC to many pod mapping.
> 
> Does [this](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1569781401) solution work for you? If not, what would be the reason to have a single PV?

In my case, EKS on fargate doesn't support EBS as PV ([link](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html#:~:text=You%20can%20run%20the%20Amazon%20EBS%20CSI%20controller%20on%20Fargate%2C%20but%20you%20can%27t%20mount%20volumes%20to%20Fargate%20Pods.)).
So I have to use EFS as the persistent volume, so it would be great if there is an option on Weaviate to specify the single volume claim for all the pods.

**Comment by vishalrv1904** [comment]
> Hi @vishalrv1904
> 
> > So I have to use EFS as the persistent volume, so it would be great if there is an option on Weaviate to specify the single volume claim for all the pods. As per my understanding, we can have one PV to one PVC mapping and one PVC to many pod mapping.
> 
> Does [this](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1569781401) solution work for you? If not, what would be the reason to have a single PV?

Tried it but still facing the same issue [this](https://github.com/weaviate/weaviate-helm/issues/148#issue-1732012070)

One pod is running perfectly but another pod is failing with a readiness exception 

```Readiness probe failed: Get "http://<IP>:8080/v1/.well-known/ready": dial TCP <IP>:8080: connect: connection refused```

**Comment by vishalrv1904** [comment]
I found the below warning on the first pod
``` {"action":"cluster_attempt_join","error":"lookup weaviate-headless.default.svc.cluster.local: no such host","level":"warning","msg":"specified hostname to join cluster cannot be resolved. This is fineif this is the first node of a new cluster, but problematic otherwise.","remote_hostname":"weaviate-headless.default.svc.cluster.local","time":"2023-06-03T20:53:54Z"} ```

**Comment by StefanBogdan** [comment]
@vishalrv1904 note that the solution I proposed [here](https://github.com/weaviate/weaviate-helm/issues/148#issuecomment-1569781401) is to have EFS. The `storage.storageClassName` is set to `efs-sc` which is a custom one create like this:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
```

Alternatively you can leave the storage class empty (`""`) so The PVs will be provisioned using the `default` Storage Class. This solution that I propose is one PV per weaviate Pod.

I am still curious WHY would you prefer having a single PV for all Pods so we can understand if that will not break Weaviate and if we need to adjust the helm chart.

Thanks!

**Comment by StefanBogdan** [comment]
@vishalrv1904 @shivam1410 as you already noticed we do not support a single PVC for all pods but it is still strange that even one PVC per pod does not work on Fargate. We will have to run some tests ourselves to understand what is going wrong. Once we run some tests we will get back to you with some answers.

cc @antas-marcin

**Comment by vishalrv1904** [comment]
Thanks for your response @StefanBogdan. 
Feel free to schedule a call if you are unable to replicate the issue on AWS EKS fargate with EFS as PV.

**Comment by StefanBogdan** [comment]
Hi @shivam1410 @vishalrv1904 I have finally done some test and have some results for you. Since EFS is already a shared Volume it does not matter if you have one PV per Pod or one PV for all Pods. During my tests I have encountered the same issue, this is caused exactly by this fact that the data is shared. `weaviate-0` opens the files and `weaviate-1` fails to open the too because it is locked by `weaviate-0`. In other words Weaviate would deadlock on startup if two instance would try to access the same disk/folder on disk. That is because of our use of `boltdb` for storing the schema which uses some locking on it’s db file. It doesn’t error, it just blocks. We are planning on fixing it in the future so it can error properly. We do not have plans to switch away from `boltdb` so having one PV is not an option and we will not add this to the helm-chart because of the reason mentioned above.

BUT I have found a solution. You have to create different Access Points to the EFS for each PV (consequently for each `weaviate-<X>` instance) AND each Access Point MUST have a different `root-directory` so Each Pod has its own files. Here is a summary that I wrote after my tests:

If planning on using Weaviate with EFS you need to:
1. Create an EFS file system.
2. Create an EFS access point for every Weaviate replica, all of the Access Points must have a different root-directory so Pods do not share the data, otherwise it will fail.
3. Create EFS mount targets for each subnet of the VPC where Weaviate is deployed.
4. Create StorageClass in kuberetes using EFS.
5. Create Weaviate Volumes, where each volume has a different AccessPoint for VolumeHandle(as mentioned above).
6. Deploy Weaviate.

Here is an example of how the PV should look like for `weaviate-0` Pod (change `weaviate-0` to `weaviate-<X>` for the other Pods/PV):
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-0 
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "efs-sc"
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <FileSystemId>::<AccessPointId-for-weaviate-0-Pod>
  claimRef:
    namespace: <namespace where Weaviate is/going to be deployed>
    name: weaviate-data-weaviate-0
```

I am closing this Issue.

**Comment by kvbutler** [comment]
> Hi @shivam1410 @vishalrv1904 I have finally done some test and have some results for you. Since EFS is already a shared Volume it does not matter if you have one PV per Pod or one PV for all Pods. During my tests I have encountered the same issue, this is caused exactly by this fact that the data is shared. `weaviate-0` opens the files and `weaviate-1` fails to open the too because it is locked by `weaviate-0`. In other words Weaviate would deadlock on startup if two instance would try to access the same disk/folder on disk. That is because of our use of `boltdb` for storing the schema which uses some locking on it’s db file. It doesn’t error, it just blocks. We are planning on fixing it in the future so it can error properly. We do not have plans to switch away from `boltdb` so having one PV is not an option and we will not add this to the helm-chart because of the reason mentioned above.
> 
> BUT I have found a solution. You have to create different Access Points to the EFS for each PV (consequently for each `weaviate-<X>` instance) AND each Access Point MUST have a different `root-directory` so Each Pod has its own files. Here is a summary that I wrote after my tests:
> 
> If planning on using Weaviate with EFS you need to:
> 
> 1. Create an EFS file system.
> 2. Create an EFS access point for every Weaviate replica, all of the Access Points must have a different root-directory so Pods do not share the data, otherwise it will fail.
> 3. Create EFS mount targets for each subnet of the VPC where Weaviate is deployed.
> 4. Create StorageClass in kuberetes using EFS.
> 5. Create Weaviate Volumes, where each volume has a different AccessPoint for VolumeHandle(as mentioned above).
> 6. Deploy Weaviate.
> 
> Here is an example of how the PV should look like for `weaviate-0` Pod (change `weaviate-0` to `weaviate-<X>` for the other Pods/PV):
> 
> ```yaml
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: weaviate-0 
> spec:
>   capacity:
>     storage: 8Gi
>   volumeMode: Filesystem
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Delete
>   storageClassName: "efs-sc"
>   csi:
>     driver: efs.csi.aws.com
>     volumeHandle: <FileSystemId>::<AccessPointId-for-weaviate-0-Pod>
>   claimRef:
>     namespace: <namespace where Weaviate is/going to be deployed>
>     name: weaviate-data-weaviate-0
> ```
> 
> I am closing this Issue.

Thanks @StefanBogdan this was helpful **BUT** for others you have to create the directories in EFS first else you will get a permission error `b'mount.nfs4: access denied by server while mounting 127.0.0.1:/'`. I'm working through setting up an init container that connects to the root of EFS drive and creates the directories if non-existent.
