### ISSUE TITLE
Pod Priority 

### ISSUE THREAD

**Issue by ahsanemon** [weaviate/weaviate-helm#172]
Right now configuring [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) for any of the services is not supported. Consequently, there is no way to prioritize the scheduling of Weaviate pods over lower-priority Pods at the moment.

**Comment by antonmatsiuk** [comment]
@StefanBogdan any updates on this?

**Comment by StefanBogdan** [comment]
Hi @antonmatsiuk , sorry I did not get back to you. Sure thing, I will get to the PR some time this week.

**Comment by antonmatsiuk** [comment]
@StefanBogdan any updates on this?

**Comment by StefanBogdan** [comment]
@antonmatsiuk I merged the PR. We are about to do a new release for weaviate helm and this is going to be part of the release!
