### ISSUE TITLE
Host weaviate.default.svc.cluster.local not reachable?

### ISSUE THREAD

**Issue by fidsusj** [weaviate/weaviate-helm#182]
I'm just trying out to host weaviate myself on a Kubernetes cluster using [this guide](https://weaviate.io/developers/weaviate/installation/kubernetes). I enabled the `text2vec-contextionary` module in the `values.yaml`, but the creation of the pod fails with:

```
{"action":"extensions_retrieve_all","error":"Get http://weaviate.default.svc.cluster.local/v1/modules/text2vec-contextionary/extensions-storage/: dial tcp 100.106.81.6:80: connect: connection refused","level":"error","msg":"","time":"2023-11-03T09:30:22Z"}
```
I also cannot ping the host locally, could you please check?

**Comment by masfrin** [comment]
I've also run into this issue and narrowed it down to the probes in contextionaryDeployment.yaml
https://github.com/weaviate/weaviate-helm/blob/ac4b60033683ddbe26f509f0c876f42556334035/weaviate/templates/contextionaryDeployment.yaml#L51-L63
These will lead the contextionary pod to not accept connections (readinessProbe failing) and to constantly restart (livenessProbe fainling).

__Commenting theses lines out or removing them will remedy the issue for now.__

---

The process `/contextionary-server` in the container is actually listening on port 9999 but I'm not sure if any HTTP endpoints are configured, see also [server.go](https://github.com/weaviate/contextionary/blob/master/server/server.go#L22)

**Comment by jgoldin-skillz** [comment]
I believe @masfrin is correct -- I'm seeing the same issue in our k8s cluster and had to remove the bad HTTP readiness probe to ensure contextionary would start. Without contextionary coming up healthy, Weaviate fails its health check and refuses connections to the Service.
