### ISSUE TITLE
storageClassName improvements

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate-helm#99]
Currently storageClassName has a default to `premium-rwo` (which only works in GCP) which is [confusing](https://weaviate.slack.com/archives/C02RRQP23K3/p1673811200484719) to users.

https://github.com/semi-technologies/weaviate-helm/blob/08e3d5e3634fa78785cf757e62c41d1bee5b23a3/weaviate/values.yaml#L54

We need additional documentation to use different values for Azure i.e. `managed-csi-premium`, and AWS `gp2`. I wonder if we should set this field blank to force users to choose? cc @etiennedi

**Comment by StefanBogdan** [comment]
Maybe we can set it to `default`, which (I think) works with Azure/AWS/GCP.
